<div class="container">
	<h3>Да здравствует русский чат - самый гуманый чат в мире!</h3>
	<div class="row">
		<div class="col-md-7 message_field" style = "
									height: 50vh;
									border: 2px solid #777;
									overflow-y: scroll;
									border-radius: 10px;
								">
			<?= getChatArray('chat.txt') ?>
		</div>
		<div class="col-md-1"></div>
		<form role="form" class="col-md-4" method="POST" action="regHandler2.php">
			<h2>Авторизуйтесь пожалуйста</h2>
			<div class="form-group">
				<label for="userLogin">Логин</label>
				<input class="form-control" name="userLogin" type="text" placeholder="Логин" required />
			</div>

			<div class="form-group">
				<label for="email">Почта</label>
				<input class="form-control" name="email"  type="email" placeholder="Ваша почта" required />
			</div>

			<textarea name="about" class="form-control" id="about_text_area1" rows="3" placeholder="Ваше сообщение"></textarea><br/>
			<button type="submit" class="btn btn-default">Отправить</button>
		</form>

	</div>
</div>
